# Chapter3 基于NumPy的数组运算

▲清单 3.1 NumPy 的导入

In [1]:
import numpy as np

▲清单 3.2 一维数组的创建

In [2]:
import numpy as np

x = np.array([1, 2, 3, 4])

print(type(x))
print(x.ndim)
print(x.shape)

<class 'numpy.ndarray'>
1
(4,)


▲清单 3.3 二维数组的创建①

In [3]:
x = np.array([1, 2, 3, 4], ndmin=2)

print(x)
print(x.shape)

[[1 2 3 4]]
(1, 4)


▲清单 3.4 二维数组的创建②

In [4]:
y = np.array([[1],
              [2],
              [3]])
              
print(y)
print(y.shape)

[[1]
 [2]
 [3]]
(3, 1)


▲清单 3.5 数组的创建

In [5]:
data = [1.0, 2, 3, 4]

x = np.array(data)
x

array([1., 2., 3., 4.])

▲清单 3.6 dtype 属性的示例

In [6]:
x.dtype

dtype('float64')

▲清单 3.7 数据类型的类名称的一览表

In [7]:
np.sctypes

{'int': [numpy.int8, numpy.int16, numpy.int32, numpy.int64],
 'uint': [numpy.uint8, numpy.uint16, numpy.uint32, numpy.uint64],
 'float': [numpy.float16, numpy.float32, numpy.float64],
 'complex': [numpy.complex64, numpy.complex128],
 'others': [bool, object, bytes, str, numpy.void]}

▲清单 3.8 指定数据类型的示例

In [8]:
y = np.array(data, dtype=np.int)

print(y)
print(y.dtype)

[1 2 3 4]
int32


▲清单 3.9 astype 方法的示例

In [9]:
# np.array(y, dtype=np.comlex) でも可
# np.complex128(y) でも可
y.astype(np.complex)

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

▲清单 3.10 ones 函数的示例

In [10]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

▲清单 3.11 full 函数的示例

In [11]:
np.full((2, 3), -1)

array([[-1, -1, -1],
       [-1, -1, -1]])

▲清单 3.12 empty 函数的示例

In [12]:
x = np.empty((4, 3))
x

array([[1.06203510e-311, 2.81617418e-322, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 6.82116729e-043],
       [6.19532414e-091, 1.05118281e-046, 2.83067004e-033],
       [3.43833585e+179, 6.48224659e+170, 4.93432906e+257]])

▲清单 3.13 zeros_like 函数的示例

In [13]:
np.zeros_like(x)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

▲清单 3.14 identity 函数的示例

In [14]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

▲清单 3.15 diag 函数的示例

In [15]:
np.diag([1, 2, 4], k=-1)

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 4, 0]])

▲清单 3.16 tri 函数的示例

In [16]:
np.tri(3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

▲清单 3.17 tril 函数的示例

In [17]:
x = np.array([[2, -3],
              [3, 4]])
              
np.tril(x)

array([[2, 0],
       [3, 4]])

▲清单 3.18 arange 函数的示例

In [18]:
np.arange(1, 6, 2)

array([1, 3, 5])

▲清单 3.19 linspace 函数

In [19]:
np.linspace(0, 1, 5, endpoint=False)

array([0. , 0.2, 0.4, 0.6, 0.8])

▲清单 3.20 logspace 函数的示例

In [20]:
np.logspace(0, 3, 4, base=np.e)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

▲清单 3.21 使用切片访问元素

In [21]:
import numpy as np

x = np.arange(10)

x[:4]

array([0, 1, 2, 3])

▲清单 3.22 使用二维数组访问元素

In [22]:
x = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
              
x[1, 2]

6

▲清单 3.23 对二维数组进行切片处理

In [23]:
x[:, 2]

array([3, 6, 9])

▲清单 3.24 确认视图

In [24]:
x = np.array([1, 2, 3, 4, 5])
y = x[:3]

y[:] = 0

print(y)
print(x)

[0 0 0]
[0 0 0 4 5]


▲清单 3.25 确认副本

In [25]:
x = np.array([1, 2, 3, 4, 5])
y = x[:3].copy()

y[:] = 0

print(y)
print(x)

[0 0 0]
[1 2 3 4 5]


▲清单 3.26 使用整数数组作为索引的示例

In [26]:
x = np.array([-1, 2, -3, 4])
y = np.array([[1, 2, 3],
              [4, 5, 6]])

#从x中提取1和3位置上的元素
print(x[[1, 3]])
              
#从y中提取(0,0),(1,2)位置上的元素
print(y[[0, 1], [0, 2]])

[2 4]
[1 6]


▲清单 3.27 使用布尔数组作为索引的示例

In [27]:
x = np.array([1, 3, 5, 7])

print(x > 4)
print(x[x > 4])

[False False  True  True]
[5 7]


▲清单 3.28 reshape 函数的示例

In [28]:
import numpy as np

x = np.array([[1, 2],
              [3, 4]])
              
y = x.reshape(4)
y

array([1, 2, 3, 4])

▲清单 3.29 使用 np.newaxis 扩展维度

In [29]:
# np.expand_dims(y, axis=1) でも可
y[:, np.newaxis]

array([[1],
       [2],
       [3],
       [4]])

▲清单 3.30 vstack 函数的示例

In [30]:
x = np.arange(4)

np.vstack((x, x, x))

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

▲清单 3.31 stack 函数的示例

In [31]:
np.stack((x, x, x), axis=1)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

▲清单 3.32 block 函数的示例

In [32]:
A = np.eye(2)
B = np.zeros((2, 3))
C = np.ones((3, 2))
D = np.eye(3) * 2

np.block([[A, B],
          [C, D]])

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 1., 2., 0., 0.],
       [1., 1., 0., 2., 0.],
       [1., 1., 0., 0., 2.]])

▲清单 3.33 tile 函数的示例

In [33]:
x = np.arange(6).reshape(2, 3)

np.tile(x, (2, 1))

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

▲清单 3.34 repeat 函数的示例

In [34]:
np.repeat(x, 3, axis=1)

array([[0, 0, 0, 1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4, 5, 5, 5]])

▲清单 3.35 T 属性的示例

In [35]:
# np.transpose(x) 也是可以的
x.T

array([[0, 3],
       [1, 4],
       [2, 5]])

▲清单 3.36 swapaxes 方法的示例

In [36]:
x.swapaxes(0, 1)

array([[0, 3],
       [1, 4],
       [2, 5]])

▲清单 3.37 在相同形状的数组之间进行运算

In [37]:
import numpy as np

x = np.array([[1, -1],
              [3, 2]])
y = np.array([[0, 1],
              [-2, 1]])
              
x + y

array([[1, 0],
       [1, 3]])

▲清单 3.38 广播的示例①

In [38]:
x = np.array([[1, 2],
              [3, 4]])
y = np.array([[5, 6]])

# 每一行都加上[5, 6]
x + y

array([[ 6,  8],
       [ 8, 10]])

▲清单 3.39 广播的示例②

In [39]:
x = np.array([[1, 2]])
y = np.array([[3],
              [4]])
              
x + y

array([[4, 5],
       [5, 6]])

▲清单 3.40 广播的示例③

In [40]:
x = np.array([[1, 2, 3],
              [4, 5, 6]])
y = np.array([0, 10, 100])

x + y

array([[  1,  12, 103],
       [  4,  15, 106]])

▲清单 3.41 广播的示例④

In [41]:
x = np.array([[1, 2],
              [3, 4]])
y = 1

x + y

array([[2, 3],
       [4, 5]])

▲清单 3.42 通用函数的使用示例

In [42]:
x = np.arange(5)

np.sqrt(x)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

▲清单 3.43 比较数组的示例

In [43]:
x = np.array([1, 2, 3, 4])
y = np.array([4, 3, 2, 1])

z = x > y
z

array([False, False,  True,  True])

▲清单 3.44 布尔值数组的筛选

In [44]:
x[(2 <= x) & (x < 4)] = 0
x

array([1, 0, 0, 4])

▲清单 3.45 all 函数的示例

In [45]:
np.all(z)

False

▲清单 3.46 使用布尔值数组的算术运算

In [46]:
x = np.array([1, 2, 3, 4])

x * (x > 2)

array([0, 0, 3, 4])

▲清单 3.47 数组的创建

In [47]:
A = np.array([[1, -2],
              [2, 0]])
B = np.array([[3, 4],
              [-1, -3]])

▲清单 3.48 矩阵乘积的示例①

In [48]:
A @ B

array([[ 5, 10],
       [ 6,  8]])

▲清单 3.49 矩阵乘积的示例②

In [49]:
x = np.array([[1, -1]]).T

A @ x

array([[3],
       [2]])